# Generated by Django 3.0.1 on 2019-12-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kitaplarim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=500)),
                ('yazar', models.CharField(max_length=500)),
                ('konu', models.CharField(max_length=500)),
                ('notlarim', models.CharField(max_length=1500)),
                ('okudugum_sene', models.DateField()),
                ('basim_yili', models.DateField(blank=True, null=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='myBooks')),
                ('eklenme_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
